### PR TITLE
Guides for devs of other languages

### LINKED ISSUE #17: Tokio for $OTHER_LANGUAGE Developers
There are other "documentation" that could be helpful, but may be best left to the community. It could be nice to encourage others to write about certain topics and link to them. 

For example: Tokio for $OTHER_LANGUAGE Developers.

### PR DESCRIPTION
**Pull request by rylev**
Attempts to fix #17 

@carllerche I'm not sure if this is the right place, but it seems to fit the theme of the section. Currently I have the per language guide at the top level of the section, but we could also have one section dedicated to guides for every language we want to support. Thoughts?

### CODE REVIEW

**Comment by carllerche** [comment]
Interesting. I did not consider adding it to the "Tokio for..." section, but it seems like it might work there.

Do you have thoughts on what would go in a "Tokio for JS devs" section?

**Comment by rylev** [comment]
I think it would be best to talk through the differences of between how Tokio works and how callback based or promised based APIs work. I even wonder if some comparisons of how to do things in JavaScript vs in Tokio would be nice (e.g., timers vs. setTimeout).

**Comment by carllerche** [comment]
👍 could you add a rough outline of what your thoughts are to this PR?

**Comment by rylev** [comment]
@carllerche Added it. Not sure it's the right set of things to talk about, but we can refine it as we go.

**Pull request merged**
